# Generated by Django 4.2.1 on 2023-06-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsapp', '0003_alter_country_options_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.TextField(max_length=100),
        ),
    ]
