# Generated by Django 4.2.1 on 2023-06-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillsapp', '0004_alter_city_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skillsapp.city'),
            preserve_default=False,
        ),
    ]
